version: "3.8"
services:
  employees-service:
    image: mmbarek/employees-service
    container_name: employees-service
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cma-config-server:8088/
      - SPRING_PROFILES_ACTIVE=cloud,rabbit,tracing
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-discovery-service:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    restart: on-failure
    depends_on:
      eureka-discovery-service: { condition: service_healthy }
      cma-config-server: { condition: service_healthy }
      cma-api-gateway: { condition: service_healthy }
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  projects_postgres:
    image: postgres:13.1-alpine
    container_name: projects_postgres
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_ENCODING=UTF8
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  projects-service:
    image: mmbarek/project-management-service
    container_name: projects_service
    depends_on:
      eureka-discovery-service: {condition: service_healthy}
      cma-config-server: {condition: service_healthy}
      cma-api-gateway: { condition: service_healthy }
      projects_postgres: {condition: service_healthy}
      employees-service: {condition: service_started}

    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cma-config-server:8088/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://projects_postgres:5432/postgres
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=postgres,cloud,rabbit,tracing
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-discovery-service:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  car-fleet-service:
    image: mmbarek/car-fleet-service
    container_name: car-fleet-service
    environment:
      - SPRING_PROFILES_ACTIVE=cloud,rabbit,tracing
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
      - KEYCLOAK_HOST=host.docker.internal
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-discovery-service:8761/eureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cma-config-server:8088/
    restart: on-failure
    depends_on:
      eureka-discovery-service: { condition: service_healthy }
      cma-config-server: { condition: service_healthy }
      cma-api-gateway: { condition: service_healthy }
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  employees-webapp:
    image: mmbarek/employees-webapp
    container_name: employees-webapp
    depends_on:
      - projects-service
      - employees-service
      - car-fleet-service
    ports:
      - 4200:80
    environment:
      - PROJECTS_API_URL=http://localhost:${API_GATEWAY_PORT}/pms
      - EMPLOYEES_API_URL=http://localhost:${API_GATEWAY_PORT}/ems
      - CAR_FLEET_API_URL=http://localhost:${API_GATEWAY_PORT}/cms

volumes:
  postgresqldata:
    external: false
