apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  #type: ClusterIP
  type: NodePort
  selector:
    component: config-server
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 32088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
      matchLabels:
          component: config-server
  template:
      metadata:
          labels:
            component: config-server
      spec:
          containers:
              - name: config-server
                image: mmbarek/cma-configserver
                ports:
                  - containerPort: 8088
                env:
                  - name: SPRING_PROFILES_ACTIVE
                    value: "rabbit,k8s"
                  - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
                    value: "https://github.com/mambarek/cma-config-repo"
                  - name: SPRING_RABBITMQ_HOST
                    value: "rabbitmq"
                  #- name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                  #  value: "http://eureka:eureka@eureka-discovery-service:8761/eureka/"  
