apiVersion: v1
kind: Service
metadata:
  name: eureka-discovery-service
spec:
  #type: ClusterIP
  type: NodePort
  selector:
    component: eureka-discovery
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 32761
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-discovery
spec:
    replicas: 1
    selector:
        matchLabels:
            component: eureka-discovery
    template:
        metadata:
            labels:
                component: eureka-discovery
        spec:
            containers:
                - name: eureka-discovery
                  image: mmbarek/eureka-discovery-service
                  ports:
                    - containerPort: 8761
