apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  #type: ClusterIP
  type: NodePort
  selector:
    component: webapp-server
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 32080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-server
spec:
  replicas: 1
  selector:
      matchLabels:
          component: webapp-server
  template:
      metadata:
          labels:
            component: webapp-server
      spec:
          containers:
              - name: webapp-server
                image: mmbarek/employees-webapp
                ports:
                  - containerPort: 80
                env:
                  - name: PROJECTS_API_URL
                    value: "http://192.168.243.252:32288/pms"
                  - name: EMPLOYEES_API_URL
                    value: "http://192.168.243.252:32288/ems"
                  - name: CAR_FLEET_API_URL
                    value: "http://192.168.243.252:32288/cms"  
  
