apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
spec:
  #type: ClusterIP
  type: NodePort
  selector:
    component: zipkin-server
  ports:
    - port: 9411
      targetPort: 9411
      nodePort: 32411
---      
apiVersion: apps/v1
kind: Deployment
metadata:
    name: zipkin-server
spec:
    replicas: 1
    selector:
        matchLabels:
            component: zipkin-server
    template:
        metadata:
            labels:
                component: zipkin-server
        spec:
            containers:
                - name: zipkin-server
                  image: openzipkin/zipkin
                  ports:
                    - containerPort: 9411
